In [4]:
# 엠보싱 필터링
import cv2 as cv
import numpy as np


src = cv.imread("rose.bmp", cv.IMREAD_GRAYSCALE)

if src is None:
    print("Image load failed!")
    exit()
    
emboss = np.array([[-1, -1, 0], 
                  [-1, 0, 1],
                  [0, 1, 1]], np.float32)

dst = cv.filter2D(src, -1, emboss, delta=128)

cv.imshow("src", src)
cv.imshow("dst", dst)
cv.waitKey()
cv.destroyAllWindows()



In [12]:
# 블러링 필터
# 실행해보면 점점 흐릿해짐
import cv2 as cv
import numpy as np

def blurring_mean():
    src = cv.imread('rose.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return
    cv.imshow('src', src)
    
    for ksize in range(3, 9, 2):
        dst = cv.blur(src, (ksize, ksize))
        
        desc = "Mean: %dx%d"%(ksize, ksize)
        cv.putText(dst, desc, (10, 30), cv.FONT_HERSHEY_COMPLEX,
                   1.0, 255, 1, cv.LINE_AA)
        cv.imshow('dst', dst)
        cv.waitKey()
    cv.destroyAllWindows()

blurring_mean()

In [1]:
import cv2 as cv
import numpy as np

def blurring_gaussian():
    src = cv.imread('rose.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print("image open failed!")
        return

    cv.imshow('src', src)
    
    for sigma in range(1, 6):
        dst = cv.GaussianBlur(src, (0, 0), sigma)
        desc = "Gaussian: sigma = %d"%(sigma)
        cv.putText(dst, desc, (10, 30), cv.FONT_HERSHEY_SCRIPT_SIMPLEX,
                   1.0, 255, 1, cv.LINE_AA)
        cv.imshow('dst', dst)
        cv.waitKey()
    cv.destroyAllWindows()
blurring_gaussian()



In [3]:
# 언샤프 마스크 필터
import cv2 as cv
import numpy as np

src = cv.imread("rose.bmp", cv.IMREAD_GRAYSCALE) 

if src is None:
    print("Image open failed!")
    exit()
    
cv.imshow('src', src)

for sigma in range(1, 6):
    blurred = cv.GaussianBlur(src, (0, 0), sigma)
    alpha = 1.0
    dst = cv.addWeighted(src, 1 + alpha, blurred, -alpha, 0.0)
    
    desc = "sigma: %d" % sigma
    cv.putText(dst, desc, (10, 30), cv.FONT_HERSHEY_SIMPLEX,
                1.0, 255, 1, cv.LINE_AA)
    cv.imshow('dst', dst)
    cv.waitKey()
cv.destroyAllWindows() 
    



In [5]:
# 영상과 잡음 모델 -> 잡음을 랜덤으로 생성해보자
import cv2 as cv
import numpy as np

def noise_gaussian():
    src = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image load failed!')
        return

    cv.imshow('src', src)
    for stddev in [10, 20, 30]:
        noise = np.zeros(src.shape, np.int32)
        cv.randn(noise, 0, stddev)
        dst = cv.add(src, noise, dtype = cv.CV_8UC1)
        desc = 'stddev = %d' % stddev
        cv.putText(dst, desc, (10, 30), cv.FONT_HERSHEY_SIMPLEX,
                   1.0, 255, 1, cv.LINE_AA)
        cv.imshow('dst', dst)
        cv.waitKey()
    cv.destroyAllWindows()

noise_gaussian()

[[ -5 -12  19 ...   7  -5  26]
 [ 22  13  -5 ...  -1   4 -14]
 [ -1   7  18 ...  11   0   4]
 ...
 [ 11   1  -8 ...  -3  -3  10]
 [  3  -5   5 ...  -2  -5   1]
 [ 12  -6   6 ...  10 -24  17]]
[[-13 -10  10 ...   4  -4  17]
 [ -5   1  15 ...  -8  16   7]
 [-14  11  18 ...  -8  13  21]
 ...
 [ -1  31   8 ... -34  33   5]
 [ 49  22  18 ...  -7  39 -13]
 [-46 -27 -60 ... -25   1  -4]]
[[-37 -18  35 ...  -4  17  43]
 [ 22 -21  15 ... -28  10  17]
 [ 20  16 -43 ...  16 -16   1]
 ...
 [ 25 -69 -23 ... -22 -21  10]
 [  4  10 -13 ... -17 -38 -15]
 [-17   8  48 ...   0  25  -9]]


: 

In [1]:
# 양방향 필터
import cv2 as cv
import numpy as np

def filter_bilateral():
    src = cv.imread('lenna.bmp',cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print('Image open failed!')
        return
    noise = np.zeros(src.shape, np.int32)
    cv.randn(noise, 0, 5)
    cv.add(src, noise, src, dtype=cv.CV_8UC1)
    
    dst1 = cv.GaussianBlur(src, (0,0), 5)
    dst2 = cv.bilateralFilter(src, -1, 10, 5)
    
    cv.imshow('src', src)
    cv.imshow('dst1', dst1)
    cv.imshow('dst2', dst2)
    cv.waitKey()
    cv.destroyAllWindows()

filter_bilateral()

In [2]:
# 미디언 필터 (솔트 앤 페퍼)
import cv2 as cv
import numpy as np
import random

def filter_median():
    src = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    if src is None:
        print('Image open failed!')
        return
    
    for i in range(0, int(src.size / 10)):
        x = random.randint(0, src.shape[1] - 1)
        y = random.randint(0, src.shape[0] - 1)
        src[x, y] = (i % 2) * 255
    
    dst1 = cv.GaussianBlur(src, (0, 0), 1)
    dst2 = cv.medianBlur(src, 3)
    
    cv.imshow('src', src)
    cv.imshow('dst1', dst1)
    cv.imshow('dst2', dst2)
    cv.waitKey()
    cv.destroyAllWindows()
    
filter_median()   

: 