In [113]:
import cv2 as cv # unsigned char -> 부호가 없는 즉 음수가아닌 정수로.

img = cv.imread('lenna.jpeg',cv.IMREAD_GRAYSCALE)

if img is None:
    print("image load failed")
    exit()

img[:,img.shape[1]//2:] = 255 - img[:,img.shape[1]//2:]
# img[img.shape[0]//2:,:] = 255 - img[img.shape[0]//2:,:]
cv.imshow('image',img)
cv.waitKey()
cv.destroyAllWindows()

In [111]:
import numpy as np
nums = np.array([[[1, 4, 2], [5, 6, 4]], [[7, 5, 3], [8, 2, 9]]])
arr = nums.transpose(0,2,1) # 큰 배열 그대로 열을 행으로 , 행을 열로 순
print(arr)
print(arr.shape, arr[1, 1, 0])

[[[1 5]
  [4 6]
  [2 4]]

 [[7 8]
  [5 2]
  [3 9]]]
(2, 3, 2) 5


In [66]:
import numpy as np
nums = np.array([[[1, 4, 2], [5, 6, 4]], [[7, 5, 3], [8, 2, 9]]])
arr = nums.reshape(2,3,2) # 큰 배열 그대로 열을 행으로 , 행을 열로 순
print(arr)
print(arr.shape, arr[1, 1, 0])

[[[1 4]
  [2 5]
  [6 4]]

 [[7 5]
  [3 8]
  [2 9]]]
(2, 3, 2) 3


In [ ]:
# 컬러 히스토그램 평활화 -> YCrCb를 사용해서
import cv2 as cv
import numpy as np

src = cv.imread('pepper.bmp', cv.IMREAD_COLOR)

if src is None:
    print('Image load failed!')
    exit()

src_ycrcb = cv.cvtColor(src, cv.COLOR_BGR2YCrCb)

ycrcb_planes = list(cv.split(src_ycrcb)) # 튜플이라 리스트로 변환
print(ycrcb_planes)
ycrcb_planes[0] = cv.equalizeHist(ycrcb_planes[0])

dst_ycrcb = cv.merge(ycrcb_planes)

dst = cv.cvtColor(dst_ycrcb, cv.COLOR_YCrCb2BGR)

cv.imshow('src', src)
cv.imshow('dst', dst)
cv.waitKey()
cv.destroyAllWindows()

[array([[ 30,  58,  62, ...,  75,  81,  57],
       [ 37, 119, 114, ..., 174, 161, 157],
       [ 38, 121, 115, ..., 171, 170, 158],
       ...,
       [ 28, 124, 132, ..., 199, 196, 187],
       [ 28, 121, 111, ..., 195, 193, 169],
       [ 28,  86, 127, ..., 184, 192, 196]], dtype=uint8), array([[179, 186, 191, ..., 211, 216, 173],
       [189, 179, 182, ..., 114, 110,  98],
       [191, 174, 178, ..., 109, 112,  96],
       ...,
       [174, 130, 131, ..., 115, 114, 129],
       [174, 143, 139, ..., 114, 116, 147],
       [174, 152, 137, ..., 115, 113, 129]], dtype=uint8), array([[111, 175, 175, ..., 175, 182, 198],
       [107,  87,  92, ...,  78,  86,  87],
       [107,  88,  90, ...,  83,  76,  88],
       ...,
       [112,  85,  84, ..., 114, 113,  95],
       [112,  89,  92, ..., 110, 115,  99],
       [112, 100,  89, ..., 109, 122, 114]], dtype=uint8)]


In [3]:
import numpy as np
import cv2 as cv

def func1():
    img1 = cv.imread('cat.jpeg',cv.IMREAD_GRAYSCALE)
    
    if img1 is None:
        print('Image load failed!')
        return
    print('type(img1):',type(img1))
    print('img1.shape:', img1.shape)
    
    if len(img1.shape) == 2:
        print('img1 is a grayscale image')
    elif len(img1.shape) == 3 :
        print('img1 is a truecolor image')
    cv.imshow('img1',img1)
    cv.waitKey(1)
    cv.destroyAllWindows()
    
func1()

type(img1): <class 'numpy.ndarray'>
img1.shape: (190, 266)
img1 is a grayscale image


In [4]:
import numpy as np

mat1=np.array([[0,0,0],[0,0,0],[0,0,0]])
mat2=np.array([[1,1,1],[1,1,1],[1,1,1]])
mat3=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [21]:
np.zeros((3,3,3))
np.ones((3,3,3),np.int32)
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
import numpy as np
import cv2 as cv

def func2():
    img1 = np.empty((480,640), np.uint8)
    img2 = np.zeros((480, 640, 3), np.uint8)
    img3 = np.ones((480, 640), np.int32)
    img4 = np.full((480, 640), 0, np.float32)
    
    mat1 = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,256]]).astype(np.uint8)
    mat1[0,1] = 100
    mat1[2,:3] = 200
    
    print(mat1)
func2()

[[ 11 100  13  14]
 [ 21  22  23  24]
 [200 200 200   0]]


In [29]:
# copy를 하고 다른 값을 변형할때 어떤 변수가 변하는지
import numpy as np

nums = np.array([1,4,2,5,3])
ref = nums[1:4]
cpy = nums[1:4].copy()
print(ref)
print(cpy)
nums[2] = 10
print(ref)
print(cpy)


[4 2 5]
[4 2 5]
[ 4 10  5]
[4 2 5]


In [7]:
import numpy as np
import cv2 as cv
def func3():
    img1 = cv.imread('cat.jpeg')
    img2 = img1
    img3 = img1.copy()
    
    img1[:,:] = (0, 255, 255)
    cv.imshow('img1', img1)
    cv.imshow('img2', img2)
    cv.imshow('img3', img3)
    cv.waitKey()
    cv.destroyAllWindows()
func3()

In [13]:
# 이미지 값에 +20 을 해서 밝은 이미지로 만들어 보기 + 부분으로 사진 뽑아보기
import numpy as np
import cv2 as cv

def func4():
    img1 = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    img2 = img1[200:400, 200:400]
    img3 = img1[200:400, 200:400].copy()
    print(img1.shape)
    
    img2 += 20
    cv.imshow('img1', img1)
    cv.imshow('img2', img2)
    cv.imshow('img3', img3)
    cv.waitKey(1)
    cv.destroyAllWindows()

func4()

(512, 512)


: 

In [ ]:
# 비디오를 열어보기
import cv2 as cv
cap = cv.VideoCapture(1)
if not cap.isOpened():
    print("Camara open failed!")
    exit()
    
print('Frame Width', int(cap.get(cv.CAP_PROP_FRAME_WIDTH)))
print('Frame height', int(cap.get(cv.CAP_PROP_FRAME_HEIGHT)))

Camara open failed!
Frame Width 0
Frame height 0


OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!


: 

In [2]:
# 창 닫고 싶으면 걍 파이썬 자체 pkill python 터미널에 치기.
# 반전되는 영상과, 그냥 기본영상을 띄워놓는 코드

if not cap.isOpened():
    print("Camara open failed!")
    exit()

while True:
    ret, frame = cap.read()
    
    if not ret:
        break
    
    inversed = ~frame # 255 - 원래값 해서 반전됨 (unsigned integer 한에서)
    cv.imshow('frame', frame)
    cv.imshow('inversed', inversed)
    
    if cv.waitKey(10) & 0xFF == 27:
        break

cap.release()
cv.destroyAllWindows()

: 

In [2]:
print("dd")

dd


In [17]:
# 내 카메라에 대한 초당 프레임 수 확인
import cv2 as cv
cap = cv.VideoCapture(0)
fps = cap.get(cv.CAP_PROP_FPS)
print("fps :",fps)
delay = round(1000 / fps)


fps : 30.0


In [18]:
# 카메라 사용 종료
cap.release()

# 모든 OpenCV 창 닫기
cv.destroyAllWindows()

: 

In [1]:
# 동영상 파일 처리하기
import cv2 as cv
cap = cv.VideoCapture('vide11.mp4')
if not cap.isOpened():
    print("Video open failed!")
    exit()
print('Frame width:', int(cap.get(cv.CAP_PROP_FRAME_WIDTH)))
print('Frame height:', int(cap.get(cv.CAP_PROP_FRAME_HEIGHT)))
print('Frame count:', int(cap.get(cv.CAP_PROP_FRAME_COUNT)))

fps = cap.get(cv.CAP_PROP_FPS)
print("fps", fps)
delay = round(1000/fps)

Frame width: 224
Frame height: 224
Frame count: 135
fps 25.0


In [2]:
while True:
    ret, frame = cap.read()
    
    if not ret:
        break
    inversed = ~frame
    
    cv.imshow('frame', frame)
    cv.imshow('inversed', inversed)
    
    if cv.waitKey(delay) == 27:
        break
cv.destroyAllWindows()

: 

In [ ]:
# 비디오 파일 저장하기
fourcc = cv.VideoWriter_fourcc("*DIVX")

# 동영상 파일 저장하기 (파일이름, fourcc, fps값, (너비, 높이) 순)
outputVideo = cv.VideoWriter('output.avi', fourcc, fps (w,h))

In [6]:
# 기본 영상을 읽어서 반전한 영상을 저장하기 2번실행하면 뭐 얼추 파일이 열리는듯함

import cv2 as cv
cap = cv.VideoCapture('vide11.mp4')

if not cap.isOpened():
    print("video open failed!")
    exit()

w = round(cap.get(cv.CAP_PROP_FRAME_WIDTH))
h = round(cap.get(cv.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv.CAP_PROP_FPS)

fourcc = cv.VideoWriter_fourcc(*'X264')
delay = round(1000 / fps)

outputVideo = cv.VideoWriter('output.mp4', fourcc, fps, (w,h))
if not outputVideo.isOpened():
    print('File open failed!')
    exit()

while True:
    ret, frame = cap.read()
    if not ret:
        break
    inversed = ~frame
    outputVideo.write(inversed)
    
    cv.imshow('frame',frame)
    cv.imshow('inversed',inversed)
    #imshow를 빼고 하면 아마 잘 저장될거임 맥북이라서 충돌이 좀 있다.
    
    if cv.waitKey(delay) == 27:
        break

cv.destroyAllWindows()

OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'


: 

In [3]:
import numpy as np
img = np.full((400, 400, 3), 255, np.uint8)

In [3]:
# 다양한 그리기 함수 활용

import numpy as np
import cv2 as cv

img = np.full((400,400,3), 255, np.uint8)

# 이건 직선으로 그린건데 왜 굵기가 다른지 모르겠음
cv.line(img,(50, 50), (200, 50), (0, 0, 255),1,cv.LINE_4)
cv.line(img, (50, 100), (200, 100), (255, 0, 255), 3)
cv.line(img, (50, 150), (200, 150), (255, 0, 0), 10)

# 이건 line type으로 4방향, 8방향, 안티에일리어싱으로 그린것
cv.line(img, (250, 50), (350, 100), (0, 0, 255), 1, cv.LINE_4)
cv.line(img, (250, 70), (350, 120), (255, 0, 255), 1, cv.LINE_8)
cv.line(img, (250, 90), (350, 140), (255, 0, 0), 1, cv.LINE_AA)

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [4]:
#50->150 길이만큼, 50->350 길이만큼 ... 화살표 그리기 (arrow)
import numpy as np
import cv2 as cv

img = np.full((400,400,3), 255, np.uint8)

cv.arrowedLine(img, (50, 200), (150, 200), (0, 0, 255), 1)
cv.arrowedLine(img, (50, 250), (350, 250), (255, 0, 255), 1)
cv.arrowedLine(img, (50, 300), (350, 300), (255, 0, 0), 1, cv.LINE_8, 0, 0.05)

# cv.MARKER_ 를 사용한 여러 모양 그리기
cv.drawMarker(img, (50, 350), (0, 0, 255), cv.MARKER_CROSS)
cv.drawMarker(img, (100, 350), (0, 0, 255), cv.MARKER_TILTED_CROSS)
cv.drawMarker(img, (150, 350), (0, 0, 255), cv.MARKER_STAR)
cv.drawMarker(img, (200, 350), (0, 0, 255), cv.MARKER_DIAMOND)
cv.drawMarker(img, (250, 350), (0, 0, 255), cv.MARKER_SQUARE)
cv.drawMarker(img, (300, 350), (0, 0, 255), cv.MARKER_TRIANGLE_UP)
cv.drawMarker(img, (350, 350), (0, 0, 255), cv.MARKER_TRIANGLE_DOWN)
cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [3]:
import numpy as np
import cv2 as cv

img = np.full((400, 400, 3), 255, np.uint8)

# 사각형 대각위치의 두 꼭짓점을 통해서 4각형  -1 은 안까지 채우는건가?
cv.rectangle(img, (50, 50), (150, 100), (0, 0, 255), 2) # 2 는 두깨
cv.rectangle(img, (50, 150), (150, 200), (0, 0, 128), -1) # -1 -> thickness로 내부를 채움

# 원그리기 30 60 은 반지름 같음
cv.circle(img, (300, 120), 30, (255, 255, 0), -1, cv.LINE_AA)
cv.circle(img, (300, 120), 60, (255, 0, 0), 3, cv.LINE_AA)

# 타원 그리기 ) 은 타원의 각각 x,y축 반지름  270은 x축 기준 시계방향 270도? 
cv.ellipse(img, (120, 300), (60, 30), 20, 0, 270, (255, 255, 0), cv.FILLED, cv.LINE_AA)
cv.ellipse(img, (120, 300), (100, 50), 20, 0, 360, (0, 255, 0), 2, cv.LINE_AA)

pts = np.array([[250, 250], [300, 250], [300, 300], [350, 300], [350, 350], [250, 350]])
cv.polylines(img, [pts], True, (255, 0, 255), 2)

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [8]:
import numpy as np
import cv2 as cv

img = np.full((400, 400, 3), 255, np.uint8)

# 사각형 대각위치의 두 꼭짓점을 통해서 4각형  -1 은 안까지 채우는건가?
cv.rectangle(img, (50, 50), (150, 100), (0, 0, 255), 2) # 2 는 두깨
cv.rectangle(img, (50, 150), (150, 200), (0, 0, 128), -1) # -1 -> thickness로 내부를 채움

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [9]:
import numpy as np
import cv2 as cv

img = np.full((400, 400, 3), 255, np.uint8)

# 원그리기 30 60 은 반지름 같음
cv.circle(img, (300, 120), 30, (255, 255, 0), -1, cv.LINE_AA)
cv.circle(img, (300, 120), 60, (255, 0, 0), 3, cv.LINE_AA)

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [11]:
import numpy as np
import cv2 as cv

img = np.full((400, 400, 3), 255, np.uint8)

# 타원 그리기 ) 은 타원의 각각 x,y축 반지름  270은 x축 기준 시계방향 270도? 
cv.ellipse(img, (120, 300), (60, 30), 20, 0, 270, (255, 255, 0), cv.FILLED, cv.LINE_AA)
cv.ellipse(img, (120, 300), (100, 50), 20, 0, 360, (0, 255, 0), 2, cv.LINE_AA)

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [12]:
import numpy as np
import cv2 as cv

img = np.full((400, 400, 3), 255, np.uint8)


pts = np.array([[250, 250], [300, 250], [300, 300], [350, 300], [350, 350], [250, 350]])
cv.polylines(img, [pts], True, (255, 0, 255), 2)

cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

In [13]:
import numpy as np
import cv2


img = np.full((500, 800, 3), 255, np.uint8)

cv2.putText(img, "FONT_HERSHEY_SIMPLEX", (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_PLAIN", (20, 100), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_DUPLEX", (20, 150), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_COMPLEX", (20, 200), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_TRIPLEX", (20, 250), cv2.FONT_HERSHEY_TRIPLEX, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_COMPLEX_SMALL", (20, 300), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_SCRIPT_SIMPLEX", (20, 350), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (255, 0, 255))
cv2.putText(img, "FONT_HERSHEY_SCRIPT_COMPLEX", (20, 400), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 1, (255, 0, 255))
cv2.putText(img, "FONT_HERSHEY_COMPLEX | FONT_ITALIC", (20, 450), cv2.FONT_HERSHEY_COMPLEX | cv2.FONT_ITALIC, 1, (255, 0, 0))

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()



In [14]:
import numpy as np
import cv2 as cv

img = np.full((200, 640, 3), 255, np.uint8)

text = "Hello, OpenCV"
fontFace = cv.FONT_HERSHEY_TRIPLEX
fontScale = 2.0
thickness = 1

sizeText, _ = cv.getTextSize(text, fontFace, fontScale, thickness)
org = ((img.shape[1] - sizeText[0]) // 2, (img.shape[0] + sizeText[1]) // 2)
cv.putText(img, text, org, fontFace, fontScale, (255, 0, 0), thickness)
cv.rectangle(img, org, (org[0] + sizeText[0], org[1] - sizeText[1]), (0, 255, 0), 1)

cv.imshow("image",img)
cv.waitKey()
cv.destroyAllWindows()

In [9]:
sizeText, _ = cv.getTextSize(text, fontFace, fontScale, thickness)
sizeText

(481, 43)

In [11]:
org

(79, 121)

In [16]:
# 키보드 이벤트 처리 관련 코드
import cv2 as cv
img = cv.imread("lenna.jpeg")
if img is None:
    print("Image load failed!")
    exit()
    
cv.namedWindow('aaaimg') # 단지 창만 띄워놓는 용도
cv.imshow('img', img)

while True:
    keycode = cv.waitKey()
    if keycode == ord('i') or keycode == ord("I"): 
        img = ~img # 반전?
        cv.imshow('img', img)
    elif keycode == 27 or keycode == ord('q') or keycode == ord('Q'):
        break
cv.destroyAllWindows()


In [20]:
# 마우스 이벤트 처리 실습
# 왼쪽 버튼을 누르거나 뗀 좌표를 콘솔 창에 출력
# 왼쪽 버튼을 누른 상태로 마우스 움직이면 궤적을 따라 영상 위에 노란색표시
# onMouse 함수를 선언하여 callback 함수로 지정

import cv2 as cv
def on_mouse(event, x, y, flags, param):
    global oldx, oldy
    
    if event == cv.EVENT_LBUTTONDOWN:
        oldx, oldy = x, y
        print('EVENT_LBUTTONDOWN: %d, %d' % (x, y))
        
    elif event == cv.EVENT_LBUTTONUP:
        print('EVENT_LBUTTONUP: %d, %d' % (x, y))
        
    elif event == cv.EVENT_MOUSEMOVE:
        if flags & cv.EVENT_FLAG_LBUTTON:
            cv.line(img, (oldx, oldy), (x, y), (0, 255, 255), 2)
            cv.imshow('img', img)
            oldx, oldy = x, y
img = cv.imread('lenna.jpeg')

if img is None:
    print("Image load failed!")
    exit()
    
cv.namedWindow('img')
cv.setMouseCallback('img', on_mouse)

cv.imshow('img', img)
cv.waitKey()
cv.destroyAllWindows()

EVENT_LBUTTONDOWN: 27, 9
EVENT_LBUTTONUP: 27, 9
EVENT_LBUTTONDOWN: 27, 9
EVENT_LBUTTONUP: 27, 9
EVENT_LBUTTONDOWN: 27, 9
EVENT_LBUTTONUP: 27, 9
EVENT_LBUTTONDOWN: 27, 9
EVENT_LBUTTONUP: 27, 9
EVENT_LBUTTONDOWN: 27, 9
EVENT_LBUTTONUP: 27, 9
EVENT_LBUTTONDOWN: 57, 53
EVENT_LBUTTONUP: 57, 53
EVENT_LBUTTONDOWN: 57, 53
EVENT_LBUTTONUP: 58, 53
EVENT_LBUTTONDOWN: 152, 57
EVENT_LBUTTONUP: 153, 57
EVENT_LBUTTONDOWN: 153, 57
EVENT_LBUTTONUP: 143, 116
EVENT_LBUTTONDOWN: 139, 140
EVENT_LBUTTONUP: 139, 140
EVENT_LBUTTONDOWN: 80, 69
EVENT_LBUTTONUP: 153, 67
EVENT_LBUTTONDOWN: 46, 30
EVENT_LBUTTONDOWN: 20, 136
EVENT_LBUTTONUP: 20, 136
EVENT_LBUTTONDOWN: 20, 136
EVENT_LBUTTONUP: 20, 136
EVENT_LBUTTONDOWN: 20, 136
EVENT_LBUTTONUP: 71, 138
EVENT_LBUTTONDOWN: 62, 148
EVENT_LBUTTONUP: 62, 148
EVENT_LBUTTONDOWN: 139, 126
EVENT_LBUTTONUP: 139, 126
EVENT_LBUTTONDOWN: 44, 56
EVENT_LBUTTONUP: 200, 124


In [21]:
# 트랙바 사용해보기
import numpy as np
import cv2 as cv

def saturated(value):
    if value > 255 :
        value = 255 # 0 ~ 255 의 색인 gray scale 범위 한정을 위해
    elif value < 0 :
        value = 0
    
    return value

def on_level_change(pos):
    img[:] = saturated(pos * 16)
    cv.imshow('image', img)
    
img = np.zeros((400, 400), np.uint8)

cv.namedWindow('image')
cv.createTrackbar('level', 'image', 0, 16, on_level_change)

cv.imshow('image',img)
cv.waitKey()
cv.destroyAllWindows()

        


: 

In [14]:
# 데이터 파일 저장하기
import numpy as np
import cv2 as cv
filename = 'mydata.json'
# filename = 'mydaya.xml'
# filename = 'mydaya.yml'

def writeData():
    name = 'joseph'
    age = 26
    pt1 = (100, 200)
    scores = (80, 90, 50)
    mat1 = np.array([[1.0, 1.5], [2.0, 3.2]], dtype=np.float32)
    
    fs = cv.FileStorage(filename, cv.FILE_STORAGE_WRITE)
    
    if not fs.isOpened():
        print('FIle open Failed!')
        return
    
    fs.write('name', name)
    fs.write('age', age)
    fs.write('point', pt1)
    fs.write('scores', scores)
    fs.write('data', mat1)
    
    fs.release()
    
writeData() # 이거 실행해줘야 함수호출 되는듯
    
    
 
    
    

In [19]:
# 저장한 데이터 파일 불러오기
import cv2 as cv

def readData():
    fs = cv.FileStorage(filename, cv.FILE_STORAGE_READ)
    
    if not fs.isOpened():
        print("file open failed!")
        return
    name = fs.getNode('name').string()
    age = int(fs.getNode('age').real())
    pt1 = tuple(fs.getNode('point').mat().astype(np.int32).flatten())
    scores = tuple(fs.getNode('scores').mat().flatten())
    mat1 = fs.getNode('data').mat()
    
    fs.release()
    
    print('name', name)
    print('age', age)
    print('point', pt1)
    print('scores', scores)
    print('data:')
    print(mat1)

readData()

name joseph
age 26
point (np.int32(100), np.int32(200))
scores (np.float64(80.0), np.float64(90.0), np.float64(50.0))
data:
[[1.  1.5]
 [2.  3.2]]


In [118]:
# 마스크 연산
# 마스크 영상
import cv2 as cv
def mask_setTO():
    src = cv.imread('lenna.bmp', cv.IMREAD_COLOR)
    mask = cv.imread('mask_smile.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None or mask is None :
        print("image open failed!")
        return
    
    #src[mask == 255] = (0, 0, 255) # B G R 에서 G,R섞기 
    r = np.where(mask[:, :,None] == 255, (0, 0, 255), src).astype(np.uint8)
    r = np.where(mask[:, :,None] == 255, (0, 0, 255), np.where(mask[:,:,None]==0, (255,0,0),src)).astype(np.uint8)
    cv.imshow('src',r)
    cv.imshow('mask',mask)
    cv.waitKey()
    cv.destroyAllWindows()

mask_setTO()


: 

In [30]:
# 마스크 영상 2
import cv2 as cv
def mask_copyTo():
    src = cv.imread("ch04/airplane.bmp",cv.IMREAD_COLOR)
    mask = cv.imread("ch04/mask_plane.bmp", cv.IMREAD_GRAYSCALE)
    dst = cv.imread("ch04/field.bmp",cv.IMREAD_COLOR)
    
    if src is None or mask is None or dst is None:
        print("file open failed!")
        return
    cv.imshow("basic dst",dst)
    dst[mask > 0] = src[mask > 0]
    cv.imshow('src', src)
    cv.imshow('dst', dst)
    cv.imshow('mask', mask)
    cv.waitKey()
    cv.destroyAllWindows()
    
mask_copyTo()

# 결론 누끼를 따야함
    
    

In [40]:
# 연산 시간 측정
import cv2 as cv

def time_inverse():
    src = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print("file open failed!")
        return
    dst = np.empty(src.shape, dtype = src.dtype)
    tm = cv.TickMeter()
    tm.start()

    for y in range(src.shape[0]):
        for x in range(src.shape[1]):
            dst[y, x] = 255 - src[y, x]
            
    tm.stop()
    print("Image inverse implementation took %4.3f ms" %tm.getTimeMilli())
    
    cv.imshow('src', src)
    cv.imshow('dst', dst)
    cv.waitKey()
    cv.destroyAllWindows()
    
time_inverse()

Image inverse implementation took 77.272 ms


In [42]:
# 연산 시간 측정
import cv2 as cv

def time_inverse():
    src = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    
    if src is None:
        print("file open failed!")
        return
    dst = np.empty(src.shape, dtype = src.dtype)

    tm = cv.TickMeter()
    tm.start()

    dst = ~src
    
    tm.stop()
    print("Image inverse implementation took %4.5f ms" %tm.getTimeMilli())
    
    cv.imshow('src', src)
    cv.imshow('dst', dst)
    cv.waitKey()
    cv.destroyAllWindows()
    
time_inverse()

Image inverse implementation took 1.28642 ms


In [46]:
# 유용한 openCv 함수 사용법
import cv2 as cv
import cv2
def useful_func():
    img = cv.imread('lenna.bmp', cv.IMREAD_GRAYSCALE)
    
    if img is None:
        print("file open failed!")
        return
    sug_img = np.sum(img)
    mean_img = np.mean(img, dtype=np.int32)
    print('Sum:', sug_img)
    print('Mean:',mean_img)
    minVal, maxVal, minPos, maxPos = cv.minMaxLoc(img)
    print('minVal is', minVal, 'at', minPos)
    print('maxVal is', maxVal, 'at', maxPos)
useful_func()    
    

Sum: 32518590
Mean: 124
minVal is 25.0 at (508, 71)
maxVal is 245.0 at (116, 273)


In [47]:
import numpy as np

src = np.array([[-1, -0.5, 0, 0.5, 1]], dtype=np.float32)
dst = cv.normalize(src, None, 0, 255, cv2.NORM_MINMAX, cv.CV_8U)
print('src:', src)
print('dst:', dst)

src: [[-1.  -0.5  0.   0.5  1. ]]
dst: [[  0  64 128 191 255]]


In [2]:
# 체커 보드판 규격에 맞게 
import cv2 as cv
import numpy as np

img = cv.imread("checker8_8.jpg",cv.IMREAD_GRAYSCALE)
print("img shape",img.shape)
cv.imshow("img", img)
cv.waitKey()
cv.destroyAllWindows()

img shape (612, 612)


감지된 크기: 4 x 4, 규격을 확인할 수 없습니다.


In [13]:
import cv2
import numpy as np

def detect_checkerboard_size(image_path):
    # 이미지 읽기
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 이미지 크기 가져오기
    rows, cols = gray.shape

    # 가로축에서 변화 감지
    changes_count = 0
    prev_pixel = gray[rows // 2, 0]  # 가로축 중간의 첫 번째 픽셀 값으로 초기화

    # 흑백 변화가 일어나는 지점 확인
    for col in range(1, cols):
        current_pixel = gray[rows // 2, col]
        # 픽셀 값이 바뀌면 카운트 증가 (흑->백 또는 백->흑)
        if current_pixel != prev_pixel:
            changes_count += 1
        prev_pixel = current_pixel

    # 변화 횟수를 기반으로 칸 수 계산 (변화는 경계이므로, 2로 나눠서 칸 개수를 얻음)
    num_squares_x = (changes_count // 2) + 1

    # 칸 개수에 따라 규격 판별
    if num_squares_x == 10:
        return "국제 룰: 10 x 10 크기 -> 10 x 10"
    elif num_squares_x == 8:
        return "영/미식 룰: 8 x 8 크기 -> 8 x 8"
    else:
        return f"감지된 칸 수: {num_squares_x}, 규격을 확인할 수 없습니다."

# 이미지 경로 설정
image_path = 'checker8_8.jpg'  # 이미지 파일 경로

# 체커보드 크기 판별 실행
print(detect_checkerboard_size(image_path))

감지된 칸 수: 32, 규격을 확인할 수 없습니다.


: 